services:
  flecsd:
    image: flecspublic.azurecr.io/flecs-slim:3.5.0-hedgehog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - flecsd:/var/lib/flecs
    restart: always
    network_mode: host
    command: 172.21.0.1

  webapp:
    image: flecspublic.azurecr.io/webapp:3.5.0-hedgehog
    ports:
      - "8081:80"
    depends_on:
      - flecsd
    restart: always
    extra_hosts:
      - flecs-floxy:172.21.0.1
    networks:
      flecs:
        ipv4_address: 172.21.255.254

  grafana:
    image: flecs.azurecr.io/com.grafana.grafana-oss:11.2.2
    depends_on:
      - flecsd

  flunder:
    image: flecs.azurecr.io/tech.flecs.flunder:4.0.0
    depends_on:
      - grafana

volumes:
  flecsd:

networks:
  flecs:
    name: flecs
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16